[package]
name = "lemonfiber-manifest"
version = "0.0.0"
license-file = "../../LICENSE"
publish = false
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
