#!/usr/bin/env python3
"""Every `--self-test` in `scripts/` runs before a release, or says why it cannot.

A recurring sentence in this directory is that a gate nobody has watched fail is
a gate nobody knows works, and each of these scripts answers it the same way: a
`--self-test` that breaks its own claims in turn and fails unless each one
refuses the break. Seven scripts carry one.

Nothing checked that they run. `just ci` reached exactly one of the seven, and
four of the others were proven only by a workflow that fires on a release — so a
gate that stopped working would be discovered during a release, which is the
worst moment available. `the_requirements_an_entry_names.py` was in that state:
its proof ran only after `Release` completed, and it takes a tenth of a second
and no network.

So this asks, of every script carrying `--self-test`: is it run somewhere that
happens *before* a release. `just ci` counts. A workflow on `pull_request` or
`push` counts. A workflow on `release` or `workflow_run` does not, because by
then the release is already going out.

A script that genuinely cannot be proven earlier says so here, with the reason,
the way `test_coverage_reads_every_script.py` in `lemonfiber/spec` makes an
unmeasured script declare itself. The entry is a debt with a name on it, not a
licence — which is why the reason has to say what the proof needs rather than
that it is inconvenient.

Reads the tree, decides, and prints what it found. No network.
Run:  python3 scripts/every_proof_runs.py
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent

# Events that happen before a release goes out. A proof run on one of these has
# had a chance to fail while somebody could still act on it.
IN_TIME = frozenset({"pull_request", "push", "schedule", "merge_group"})

# Scripts whose proof cannot run before a release, and what it needs instead.
#
# One entry, and it is not a matter of taste: `dist` generates the installer at
# release time and attaches it as an asset, so it is not in this tree to read.
# The self-test mutates a real installer to check each claim refuses the
# mutation, and there is nothing to mutate until the release makes one.
LATER = {
    "the_installer_places_what_it_verified.py": (
        "the installer is generated by `dist` at release time and is not in this "
        "tree; the proof mutates a real one, so there is nothing to mutate earlier"
    ),
}

# The flag being *acted on*, not merely mentioned.
#
# Matching the bare string found this file itself, which talks about
# `--self-test` throughout and at the time declared none — a detector that counts
# its own prose will count a comment in somebody else's script too.
#
# Matching only `add_argument` was the opposite mistake and the worse one. Three
# of the eight scripts here read the flag straight off `sys.argv`, and a detector
# that sees six of eight reports a clean sweep while two proofs run nowhere.
# A gate that under-counts is the failure this whole file is about, so it is held
# to both idioms and the self-test puts each in front of it.
SELF_TEST = re.compile(
    r'add_argument\(\s*"--self-test"'
    r'|"--self-test"\s+in\s+(sys\.)?argv'
)


def carries_a_proof(text: str) -> bool:
    """Whether this script acts on a `--self-test` flag, rather than mentioning one."""
    return bool(SELF_TEST.search(text))


def when(workflow: str) -> set[str] | None:
    """The events a workflow fires on, or `None` where it could not be read.

    `on` is the YAML 1.1 boolean `True` once parsed, which is a trap worth
    handling once here rather than in each caller.

    `None` rather than an empty set, and rather than an exception. A workflow
    this cannot parse is not a workflow that fires on nothing — reading it that
    way would quietly drop a proof that does run and fail the script carrying it.
    It is somebody else's problem (actionlint's), so it is reported and not
    guessed at.
    """
    try:
        parsed = yaml.safe_load(workflow) or {}
    except yaml.YAMLError:
        return None
    if not isinstance(parsed, dict):
        return None
    fires = parsed.get(True, parsed.get("on"))
    if isinstance(fires, (dict, list)):
        return set(fires)
    return {fires} if isinstance(fires, str) else set()


def proven_in_time(name: str, justfile: str, workflows: dict[str, str]) -> list[str]:
    """Where this script's proof runs early enough to be worth having.

    Returns the places, so a caller can say which rather than only whether.
    """
    call = f"{name} --self-test"
    found = []
    if call in justfile:
        found.append("justfile")
    for path, text in workflows.items():
        fires = when(text)
        if call in text and fires is not None and fires & IN_TIME:
            found.append(path)
    return found


def unproven(
    scripts: dict[str, str], justfile: str, workflows: dict[str, str]
) -> list[tuple[str, str]]:
    """Every script whose proof runs too late, and is not declared as such."""
    late = []
    for name, text in sorted(scripts.items()):
        if not carries_a_proof(text) or name in LATER:
            continue
        if not proven_in_time(name, justfile, workflows):
            late.append((name, "carries a --self-test that nothing runs before a release"))
    return late


def stale(scripts: dict[str, str]) -> list[tuple[str, str]]:
    """Declarations in `LATER` that no longer describe anything.

    A debt whose script is gone, or which gained a proof that runs in time, is a
    paragraph asserting something untrue — and the table is only worth reading if
    every line in it is still earned.
    """
    return [
        (name, "is declared as unprovable-until-release and is not in scripts/")
        for name in sorted(LATER)
        if name not in scripts
    ]


def unreadable(workflows: dict[str, str]) -> list[str]:
    """Workflows whose triggers could not be read, so nothing was concluded."""
    return [path for path, text in sorted(workflows.items()) if when(text) is None]


def read() -> tuple[dict[str, str], str, dict[str, str]]:
    scripts = {
        path.name: path.read_text(encoding="utf-8") for path in sorted(HERE.glob("*.py"))
    }
    justfile = (ROOT / "justfile").read_text(encoding="utf-8")
    workflows = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted((ROOT / ".github" / "workflows").glob("*.yml"))
    }
    return scripts, justfile, workflows


def self_test() -> int:
    """Each claim, put in front of the case that would break it.

    This gate is subject to the sentence it enforces, and the first version of it
    failed the test it was written to apply: it counted a script that talks about
    `--self-test` as one that has it, which is how it reported itself.
    """
    declares = 'ap.add_argument("--self-test", action="store_true")'
    by_argv = '    if "--self-test" in sys.argv[1:]:'
    by_bare_argv = '    testing = "--self-test" in argv'
    mentions = '# run it with --self-test to see\nprint("--self-test")'
    def workflow(events: str, call: str = "") -> str:
        return f"on:\n{events}jobs:\n  a:\n    steps:\n      - run: python3 {call}\n"

    pull = workflow("  pull_request:\n")
    release = workflow("  release:\n    types: [published]\n")

    failures = []
    if not carries_a_proof(declares):
        failures.append("a --self-test declared with argparse was not seen")
    if not carries_a_proof(by_argv):
        failures.append("a --self-test read off sys.argv was not seen")
    if not carries_a_proof(by_bare_argv):
        failures.append("a --self-test read off a bare argv was not seen")
    if carries_a_proof(mentions):
        failures.append("a script that only mentions --self-test was counted as having one")

    if when(pull) != {"pull_request"}:
        failures.append("a pull_request workflow was not read as running in time")
    if when(release) & IN_TIME:
        failures.append("a release workflow was read as running in time")
    for nothing in ("jobs: {}\n", "on: []\n", "on: 7\n"):
        if when(nothing):
            failures.append(f"{nothing!r} was read as firing on something")

    # A workflow this cannot read is not one that fires on nothing.
    for broken in ("on:\n  pull_request:\n  - a: b\n  c\n", "- just a list\n", "text"):
        if when(broken) is not None:
            failures.append(f"{broken!r} was read rather than refused")
    if unreadable({"w.yml": "- a list\n"}) != ["w.yml"]:
        failures.append("an unreadable workflow was not named")
    if unreadable({"w.yml": pull}):
        failures.append("a readable workflow was called unreadable")

    scripts = {"a.py": declares}
    runs_on_pull = workflow("  pull_request:\n", "a.py --self-test")
    runs_on_release = workflow("  release:\n", "a.py --self-test")
    if proven_in_time("a.py", "ci: scripts\n", {"w.yml": runs_on_pull}) != ["w.yml"]:
        failures.append("a proof run by a pull_request workflow was not found")
    if proven_in_time("a.py", "    python3 a.py --self-test\n", {}) != ["justfile"]:
        failures.append("a proof run by the justfile was not found")
    if proven_in_time("a.py", "", {"w.yml": runs_on_release}):
        failures.append("a proof run only at release time was called run in time")
    if proven_in_time("a.py", "", {"w.yml": "- unreadable\n" + "a.py --self-test"}):
        failures.append("a proof in a workflow that could not be read was counted")

    if not unproven(scripts, "", {}):
        failures.append("a script whose proof runs nowhere was not refused")
    if unproven({"a.py": mentions}, "", {}):
        failures.append("a script with no proof at all was asked for one")
    if unproven(scripts, "    python3 a.py --self-test\n", {}):
        failures.append("a proof that does run was refused anyway")

    if stale({"the_installer_places_what_it_verified.py": ""}):
        failures.append("a declaration whose script is present was called stale")
    if not stale({}):
        failures.append("a declaration whose script is gone was not called stale")

    for line in failures:
        print(f"self-test: {line}", file=sys.stderr)
    print("self-test: every claim holds." if not failures else "self-test: FAILED")
    return 1 if failures else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--self-test", action="store_true")
    if ap.parse_args().self_test:
        return self_test()

    scripts, justfile, workflows = read()
    wrong = unproven(scripts, justfile, workflows) + stale(scripts)
    proofs = [name for name, text in scripts.items() if carries_a_proof(text)]

    # Said out loud rather than folded into the verdict. A workflow this could
    # not read may be the one running a proof, and a pass that did not read
    # everything is worth a sentence saying so.
    for path in unreadable(workflows):
        print(
            f"::warning file=.github/workflows/{path}::could not read the triggers "
            f"of {path}, so any proof it runs was not counted.",
            file=sys.stderr,
        )

    for name, why in wrong:
        print(f"::error file=scripts/{name}::{name} {why}.", file=sys.stderr)
    if wrong:
        print(
            "A proof that only runs at release time is found broken during a "
            "release. Add it to a recipe `just ci` reaches, or to a workflow on "
            "`pull_request`; if it truly cannot run earlier, say so in `LATER` "
            "with what it needs.",
            file=sys.stderr,
        )
        return 1

    print(
        f"{len(proofs)} script(s) carry a --self-test; "
        f"{len(proofs) - len(LATER)} run before a release, "
        f"{len(LATER)} declared as needing one."
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
